esphome:
  name: esp-r8-poe-3c
  platform: ESP32
  board: esp32dev
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO17

# Manual IP.  Fill in with your specific network information.
  manual_ip:
    static_ip: 192.168.10.195
    gateway: 192.168.10.1
    subnet: 255.255.255.0
    
status_led:
  pin: GPIO14

i2c:
   - id: bus_a
     sda: 32
     scl: 33
     scan: True
   
time:
  - platform: ds1307
    update_interval: never
    id: on_board_time
  - platform: homeassistant
    id: homeassistant_time
    on_time_sync:
      then:
        ds1307.write_time:
    
        
pcf8574:
  - id: 'output_expander'
    address: 0x23
    pcf8575: False
  - id: 'input_expander'
    address: 0x25
    pcf8575: False

# Individual outputs
switch:
  - platform: gpio
    id: relay_1
    name: "Relay 1"
    pin:
      pcf8574: output_expander
      # Use pin number 0
      number: 0
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: True
      
  - platform: gpio
    name: "Relay 2"
    pin:
      pcf8574: output_expander
      # Use pin number 1
      number: 1
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: True
      
  - platform: gpio
    name: "Relay 3"
    pin:
      pcf8574: output_expander
      # Use pin number 2
      number: 2
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: True
      
  - platform: gpio
    name: "Relay 4"
    pin:
      pcf8574: output_expander
      # Use pin number 3
      number: 3
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: True
      
  - platform: gpio
    name: "Relay 5"
    pin:
      pcf8574: output_expander
      # Use pin number 4
      number: 4
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: True
      
  - platform: gpio
    name: "Relay 6"
    pin:
      pcf8574: output_expander
      # Use pin number 5
      number: 5
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: True
      
  - platform: gpio
    name: "Relay 7"
    pin:
      pcf8574: output_expander
      # Use pin number 6
      number: 6
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: True
      
  - platform: gpio
    name: "Relay 8"
    pin:
      pcf8574: output_expander
      # Use pin number 7
      number: 7
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: True
      
binary_sensor:
  - platform: gpio
    filters:
      - invert:
    pin:
      pcf8574: input_expander
      number: 0
      mode: INPUT
    name: "Input 1"
  - platform: gpio
    filters:
      - invert:
    pin:
      pcf8574: input_expander
      number: 1
      mode: INPUT
    name: "Input 2"
  - platform: gpio
    filters:
      - invert:
    pin:
      pcf8574: input_expander
      number: 2
      mode: INPUT
    name: "Input 3"
  - platform: gpio
    filters:
      - invert:
    pin:
      pcf8574: input_expander
      number: 3
      mode: INPUT
    name: "Input 4"
  - platform: gpio
    filters:
      - invert:
    pin:
      pcf8574: input_expander
      number: 4
      mode: INPUT
    name: "Input 5"
  - platform: gpio
    filters:
      - invert:
    pin:
      pcf8574: input_expander
      number: 5
      mode: INPUT
    name: "Input 6"
  - platform: gpio
    filters:
      - invert:
    pin:
      pcf8574: input_expander
      number: 6
      mode: INPUT
    name: "Input 7"
  - platform: gpio
    filters:
      - invert:
    pin:
      pcf8574: input_expander
      number: 7
      mode: INPUT
    name: "Input 8"